import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import SideBar from '@/app/ui/sidebar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
        <div className="w-full flex-none md:w-64 ">
          <SideBar />
        </div>
        <div className={inter.className}>{children}</div>
      </div>
    </html>
  );
}
