//Import external dependencies
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//Import components from ui
import SideBar from '@/app/ui/sidebar';
import Banner from "./ui/banner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        <Banner />

        <div className="flex h-screen flex-row ">
          <div className="flex flex-col">
            <SideBar />
          </div>
          <div className="flex-grow md:overflow-y-auto">{children}</div>
          
        </div>
      </body>
    </html>
    
  );
}
